height:
  - 4' 8"
  - 4' 9"
  - 4' 10"
  - 4' 11"
  - 5' 0"
  - 5' 1"
  - 5' 2"
  - 5' 3"
  - 5' 4"
  - 5' 5"
  - 5' 6"
  - 5' 7"
  - 5' 8"
  - 5' 9"
  - 5' 10"
  - 5' 11"
  - 6' 0"
  - 6' 0"
  - 6' 2"
  - 6' 3"
  - 6' 4"
  - 6' 5"
  - 6' 6"
  - 6' 7"
  - 6' 8"
  - 6' 9"
  - 6' 10"
gender:
  - Male
  - Female
body_type:
  - Slender
  - Average
  - Athletic/Toned
  - Heavyset
relationship_status:
  - Never married
  - Currently separated
  - Divorced
  - Widow/widower
has_kids:
  - Don't/doesn't have kids
  - Yes, but they live away from home
  - Yes, sometimes they live at home
  - Yes, and they live at home full-time
wants_kids:
  - Don't/doesn't want kids
  - Defintely
  - Someday
education:
  - High School/GED
  - Some college
  - Associate's Degree
  - Bachelor's Degree
  - Master's Degree
  - Doctoral Degree or PhD
is_smoker:
  - Not a smoker
  - Yes, socially
  - Yes, moderately
  - Yes, regularly
is_drinker:
  - No/Not Anymore
  - Yes, socially
  - Yes, moderately
  - Yes, regularly
salary_range:
  - $24,999 or below
  - $25,000 - $49,999 annually
  - $50,000 - $99,999 annually
  - $100,000 - $149,999 annually
  - $150,000 and above
